### ISSUE TITLE
Error in bilinear_sampler function

### ISSUE THREAD

**Issue by cjsj166** [KAIST-VCLAB/dual-pixel-disparity#2]
When I execute demo.py, error happens in utils.py.

assert torch.unique(ygrid).numel() == 1 and H == 1

This line gives an error frequently. The error doesn't even occur consistently.
I'd appreciate it if anybody can help with this.
```
def bilinear_sampler(img, coords, mode='bilinear', mask=False):
    """ Wrapper for grid_sample, uses pixel coordinates """
    H, W = img.shape[-2:]
    xgrid, ygrid = coords.split([1,1], dim=-1)
    xgrid = 2*xgrid/(W-1) - 1

    assert torch.unique(ygrid).numel() == 1 and H == 1 # This is a stereo problem  <-  This is where exception occurs, 
                                                                                   torch.unique(ygird).numel is not 1

    grid = torch.cat([xgrid, ygrid], dim=-1)
    img = F.grid_sample(img, grid, align_corners=True)

    if mask:
        mask = (xgrid > -1) & (ygrid > -1) & (xgrid < 1) & (ygrid < 1)
        return img, mask.float()

    return img
```

**Comment by michael-1003** [comment]
It seems the input image is not compatible as expected in RAFT-Stereo.
Maybe you can check the recent updates of the corresponding fix in RAFT-Stereo. [[Link]](https://github.com/princeton-vl/RAFT-Stereo/commit/ca57ab21a05675fc756ba41139dd2f9ec20c5d40#diff-3401fbdc2a8b630ac2977113a03a0c8662fc256592f402eca7dd619df9490245)
