### ISSUE TITLE
kernel in numpy format.

### ISSUE THREAD

**Issue by tuvovan** [KAIST-VCLAB/dual-pixel-disparity#3]
Hello,

Thank you for your nice work. I just have a question regarding to the kernel files. I saw that you provided the files in image format, can I have them in numpy format please? 

As far as I understand, to save kernels to images, you might scaled the original ones somehow right?

Please correct me if I'm wrong.

thank you!

**Comment by michael-1003** [comment]
Maybe you can utilize the tif data in the `separated/`. Those kernels are data before adjustment. However, since we used LED display, we made some additional adjustments, and using files in `adjusted/` or `single/` might be better.

**Comment by tuvovan** [comment]
I noticed that in the target [image](https://drive.google.com/drive/folders/1yXAR4WNuic5HuLrp2D4tFo7esdLrkais) there are 14 rows * 24 columns.
but in the captured images in `separated` folder, there are only 16 columns and 11 rows. 
can you please explain why?

Thanks!

**Comment by michael-1003** [comment]
The camera is set to capture the region of 11 x 16 area, which is smaller than the full image displayed. The reason is to make the camera capture only the target displayed.

**Comment by tuvovan** [comment]
so to get the corresponding patch of the captured 11*16 area in the full image, can I just randomly pick a 11*16 area in the full image?

thank you!

**Comment by michael-1003** [comment]
It can be, but note that some displays (usually, display with IPS panel) have backlight bleeding on their boundary. So the center region might be the best choice.

**Comment by tuvovan** [comment]
thank you. by the way, can I just use the captured images directly as kennels or do I need to estimate the kernels using the captured images and the corresponding one? like [this](https://cim.mcgill.ca/~fmannan/CRV16/Calib.pdf) paper?

**Comment by michael-1003** [comment]
If you need to use the captured image from the display as a kernel, using the additional estimation/correction step is better if it is available. Since this is an abstract method, direct usage is unpreferable.

**Comment by tuvovan** [comment]
thanks!
